CC ?= cc
CFLAGS ?= -O3 -ffast-math -march=native -DNDEBUG -Wall -Wextra -fPIC
LDFLAGS ?= -lpthread -framework Accelerate -lm

FAST_CPU_FLAGS = -DUSE_PACKED_ROW4 -DUSE_PACKED_ROW4_LOADQ -DUSE_STATIC_MATVEC_KERNELS -DUSE_LAYER0_QKV_CACHE -DUSE_LAYER0_QK_NORM_CACHE -DUSE_THREADS -DUSE_CHUNKED_MATVEC -DUSE_STATIC_POOL -DUSE_FUSED_STAGE_THREADS -DMATVEC_THREAD_MIN_OPS=32768 -DUSE_VFORCE_EXP -DVFORCE_EXP_MIN_N=128 -DUSE_ATTN_ACCUM -DUSE_ATTN_SCORE8 -DUSE_ATTN_SCORE_MAX -DUSE_ATTN_Q_PRELOAD -DUSE_FUSED_SOFTMAX_VALUES -DUSE_FUSED_EXP_VALUES -DUSE_FUSED_RESIDUAL -DUSE_FUSED_SWIGLU -DUSE_FAST_ARGMAX -DUSE_FUSED_LMHEAD_ARGMAX -DUSE_STATIC_QWEN3_2M -DUSE_MLX_BF16_RMS -DROUND_MATVEC_RMS -DUSE_REDUNDANT_RMSNORM

.PHONY: all clean

all: libqwen3_mnist_realtime.dylib

libqwen3_mnist_realtime.dylib: qwen3_mnist_realtime.c qwen3_cpu_bench.c
	$(CC) $(CFLAGS) $(FAST_CPU_FLAGS) -dynamiclib $< -o $@ $(LDFLAGS)

clean:
	rm -f libqwen3_mnist_realtime.dylib
